### ISSUE TITLE
Threads Icon

### ISSUE THREAD

**Issue by iamjeffperry** [microdotblog/plugin-fontawesome#1]
It seems that you may need to update to the latest Font Awesome version as the Threads icon is not showing properly. After adding my own kit to the <head> of my site it worked as intended.

**Comment by manton** [comment]
Thanks, you're right, we have to update the plug-in any time there are new Font Awesome icons. I'll do a new version.

**Comment by manton** [comment]
Updated the plug-in to the latest set of icons from Font Awesome. Should be an "Upgrade" button soon or you can uninstall. re-install.
